base_url = "https://modctl.org"
title = "modctl"
description = "A package manager for your mods"

compile_sass = true
build_search_index = true

[search]
index_format = "elasticlunr_json"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
current_version = "v0.1.0"
release_url = "https://github.com/mfinelli/modctl/releases/tag/v0.1.0"
