---
name: Package
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy  # glibc floor
    steps:
      - run: apt-get update
      - run: apt-get upgrade -y
      - run: |
          apt-get install -y \
            ca-certificates \
            binutils-aarch64-linux-gnu \
            build-essential \
            debsigs \
            file \
            gcc-aarch64-linux-gnu \
            libarchive-tools \
            rpm \
            unzip
      - uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          cache: true
          go-version-file: go.mod
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: 1.30.0
      - run: sqlc generate
      - run: go install github.com/google/go-licenses/v2@latest
      - run: ./builddeb.bash
      - run: ./buildrpm.bash
      - run: go mod vendor
      - uses: actions/upload-artifact@v6
        with:
          name: deb
          path: pkg/*.deb
          retention-days: 1
      - uses: actions/upload-artifact@v6
        with:
          name: rpm
          path: pkg/rpmbuild/RPMS/**/*.rpm
          retention-days: 1
